# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdata',
            name='activeAirflow',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildingdata',
            name='idleAirflow',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
