# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='airflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilID', models.CharField(max_length=70)),
                ('typeOfFacility', models.CharField(max_length=70)),
                ('system', models.CharField(max_length=70)),
                ('vav', models.CharField(max_length=70)),
                ('areaSqft', models.IntegerField()),
                ('occupants', models.IntegerField()),
                ('raOutAirRateArea', models.IntegerField()),
                ('raOutAirRatePerson', models.IntegerField()),
                ('vbz', models.IntegerField()),
                ('ez', models.IntegerField()),
                ('voz', models.IntegerField()),
                ('ev', models.IntegerField()),
                ('vot', models.IntegerField()),
                ('leed', models.IntegerField()),
                ('leedVot', models.IntegerField()),
                ('occupiedMaxAirflow', models.IntegerField()),
                ('occupiedReqAirflow', models.IntegerField()),
                ('reqDamperPosition', models.IntegerField()),
                ('occupiedIdleAirflow', models.IntegerField()),
                ('idleDamperPosition', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='fri',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mon',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='sat',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='sun',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='thurs',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tues',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='wed',
            field=models.CharField(max_length=1),
        ),
    ]
