# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20160728_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='regdoc',
            name='buidfile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.BuildingDoc'),
            preserve_default=False,
        ),
    ]
