# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_regdoc_buidfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regdoc',
            old_name='buidfile',
            new_name='buildfile',
        ),
    ]
