# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20160730_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='MtgEnd',
            new_name='mtgEnd',
        ),
    ]
