# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20160730_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='catalog',
            field=models.CharField(max_length=20),
        ),
    ]
