# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_auto_20160730_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airdistconf',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
