# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_auto_20160730_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventrate',
            name='airRateArea',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ventrate',
            name='airRatePerson',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
