# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_auto_20160730_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysVentEfficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZpMax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Ev', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
